language: python

python: 3.7

branches:
    only:
        - master

install:
    - pip install -r requirements.txt
    - pip install nbval
    - pip freeze

jobs:
    fast_finish: true
    include:
        - name: "Chapters 00-09"
          script:
              - find notebooks -maxdepth 1 -name "0*.ipynb" | sort -n | xargs pytest -vx --nbval-lax
        - name: "Chapters 10-17"
          script:
              - find notebooks -maxdepth 1 -name "1*.ipynb" | sort -n | xargs pytest -vx --nbval-lax
