language: python

python: 3.7

branches:
    only:
        - master

install:
    - pip install -r requirements.txt
    - pip install nbval
    - pip freeze

jobs:
    fast_finish: true
    include:
        - name: "Chapters 00-12"
          script:
              - find notebooks -maxdepth 1 -name "0*.ipynb" | sort -n | xargs pytest -vx --nbval-lax
              - find notebooks -maxdepth 1 -name "1[0-2]*.ipynb" | sort -n | xargs pytest -vx --nbval-lax
        - name: "Chapters 13-17"
          script:
              - travis_wait 20 find notebooks -maxdepth 1 -name "1[3-7]*.ipynb" | sort -n | xargs pytest -vx --nbval-lax

